pipeline {
    agent any
    // options {

    // }
    stages {
        stage('Build') {
            steps {
                echo 'Build'
                docker version
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }

    }
}
